---
title: "SBA Resources"
output:
  html_document:
    df_print: paged
---

Welcome to the **unofficial** Website for Statistics for Business Administration.

Here you can find an overview over most of the formulas that are provided in the lecture together with explanations and examples.

_Note:_ This website is a Work-In-Progress. If you feel like something is missing [tell us](https://github.com/Leoniepopken/SBA/issues), write us via WhatsApp or add it yourself!

### Table of Contents

#### Summaries

---

##### Descriptive Statistics and exploratory data analysis
  1.  [Basic Concepts of Statistics](./notebooks/basic-concepts.nb.html)
  2.  [How to obtain data](./notebooks/How-to-obtain-data.nb.html)
  3.  [Feature Types and Scales](./notebooks/feature-types-and-scales.nb.html)
  4.  [Frequencies](./notebooks/frequencies.nb.html)
  5.  [Graphical Representations](./notebooks/graphicalRepresentation.nb.html)
  6.  [Cumulative Frequencies](./notebooks/cumulative-frequencies.nb.html)
  7.  [Central tendency measures](./notebooks/centraltendencymeasure.nb.html)
  8.  [Measurement of dispersion](./notebooks/MeasuresOfDispersion.nb.html)
  9.  [Joint Frequencies](./notebooks/jointFrequencies.nb.html)
  10. [Conditional Frequencies](./notebooks/conditionalFrequencies.nb.html)
  11. [Chi-squarred Coefficient](./notebooks/chiSquared.nb.html)
  12. [Contingency Coefficient](./notebooks/contingencyCoefficient.nb.html)
  13. [Empirical Covariance](./notebooks/empiricalCovariance.nb.html)
  14. [Bravais-Pearson Correlation Coefficient](./notebooks/bravais-pearson.nb.html)
  15. [Spearman‘s (Rank) Correlation Coefficient](./notebooks/spearman.nb.html)
  16. [Method of Least Squares](./notebooks/leastSquares.nb.html)
  17. [Coefficient of Determination and Residual Analysis](./notebooks/linearRegression.nb.html)

---

##### Probability calculus
  1. [Laplace Probability](./notebooks/Laplace-Probabilities.nb.html)
  2. [Calculation Rules for Probabilities](./notebooks/Calculation-Probability-Rules.nb.html)
  3. [Concept of Objective Probability](./notebooks/Concept-of-Objective-Probability.nb.html)
  4. [Conditional Probabilities](./notebooks/Conditional-Probabilities.nb.html)
  5. [Distribution Function](./notebooks/distributionFunction.nb.html)
  6. [Probability Mass Function](./notebooks/prop_Massfunction.nb.html)
  7. [Central tendency measures for discrete random variables](./notebooks/central_tendency.nb.html)
  8. [Distribution measures for discrete random variables](./notebooks/prop_distribution_measures.nb.html)
  10. [(In)dependence of continuous crandom variables](./notebooks/independenceOfRandomVariables.nb.html)
  12. Continous random variables: coming soon!
  13. [Density](./notebooks/density.nb.html)
  16. [Central tendency and dispersion measures for continuous random variables](./notebooks/centralTendencyContinuous.nb.html)

      <br>[Overview: distributions](./notebooks/overview_distributions.nb.html)

---

##### Statistical inference or inductive statistics
  1. [Point estimation](./notebooks/point_estimation.nb.html)
  2. [Unbiased estimators](./notebooks/unbiased_estimator.nb.html)
  3. [Mean squared error and consistency](./notebooks/mean_squared_error_and_consistency.nb.html)
  4. [Construction of estimation functions]
  5. [Interval estimation]

---

#### Other (Useful Documents)
1. [R Cheat Sheet](./pdfs/r-befehle.pdf) (german only)

