---
title: "Distribution Function"
output: html_notebook
---

- If the discrete random variable X is at least ordinally scaled, we can define the distribution function of X similarly to the empirical distribution function of a feature/characteristic
- For this, we assume that the values $x_1, x_2, ... , x_k, ...$ in the support of X are already sorted in ascending
order (i.e. $x_1 < x_2 < ... < x_k < ...$)

$$F(x) = P(X \le x) = \sum\limits_{i:x_i \le x} f(x_i) = \sum\limits_{i:x_i \le x} p_i$$

and $P(X \ge x) = 1 - P(X \le x) = 1 - F(x)$

- F(x) corresponds exactly to the probability that the value of the random variable X is at most x.

#### Properties
- The function F is a monotonically increasing step function
- Jump of height $p_i = f(x_i)$ at $x_i$
- At jump points, the upper value ("stair edge") is the corresponding function value
- F(x) = 0 for all $x < x_1$

---

#### For a continuos variable with density f
$$F(x) = P(X \le x) = \int_{-\infty}^{x} f(x) \; dx$$

---

#### For [continous uniform distribution](./uniformDistribution.nb.html)

$$F(x) = \int_{- \infty}^{x} f(t) \; dt = \begin{cases}
0 ,& x < a\\
\frac{x - a}{b - a} ,& a \le x \le b \\
1 ,& x > b
\end{cases} $$

---

#### For the [exponential distribution](./exponentialDistribution.nb.html)
$$F(x) = \begin{cases}
1- e^{-\lambda x} ,& x \ge 0\\
0  ,& x < 0
\end{cases} $$

---

#### For the [poisson distribution](./poissonDistri.nb.html)
(according to https://de.wikipedia.org/wiki/Poisson-Verteilung#Verteilungsfunktion)
$$F(x) = e^{-\lambda}\sum_{k = 0}^{n}\frac{\lambda ^x}{x!}$$
---

#### some calculation hints
Probabilities can be calculated via the distribution function as follows: <br>
    - $P(X > x) = 1 - P(X \le x) = 1 - F(x)$ <br>
    - $P(x < X < y) = P(X \le y) - P(X \le x) = F(y) - F(x)$ <br>
    - $P(x \le X \le y | X \le z) = \frac{P(x \le X \le y, X \le z)}{P(X \le z)} = \frac {P(x \le X \le z)}{P(X \le z)} = \frac{F(z) - F(x)}{F(z)}$ <br>
    - $P(X \le x) = F(x)$ <br>
    - $P(X \ge x) = 1 - F(x)$ <br>


[Back to Table of Contents](../)