---
title: "Overview: statistical tests"
output: html_notebook
---

A statistical test problem consists of a null hypothesis $H_0$ and an alternative hypothesis $H_1$ that are mutually exclusive and involve statements about the entire distribution or about specific parameters of a characteristic of interest in the population.
A test statistic for a statistical test problem is a function $T = g(X_1, \dots, X_n)$ of sample variables $X_1, \dots, X_n$ with the following properties:
- Sensitivity for the test problem: Based on the value $t = g(x_1, \dots, x_n)$ resulting from the realizations $x_1, \dots, x_n$ it can be judged whether $H_0$ or $H_1$ is more likely to be true for the population
- Known distribution under the null hypothesis: The distribution of T under the assumption that the null hypothesis is true (test distribution) can be determined

---

#### Steps to test a hypotheses:
1. Find $H_0$ and $H_1$
2. Find which values you have given and select a proper test
3. Calculate the test size
4. Compare your result with the rules of decision-making to find out, wether $H_0$ is rejected or not

---

#### [Approximate binomial test](./binomial_test.nb.html)
For large samples.
Can be used if the population is unknown.

---

#### [(Gaussian) Z-test for the expected value of a normal distribution](./z-test.nb.html)
$o^2$ is known, but $\mu$ unknown

---

#### [T-test for the expected value of a normal distribution](./t-test.nb.html)
$o^2$ and $\mu$ are unknown

---

#### Errors in statistical tests
$P(Error type 1) = P(H_0 rejected | H_0 true)$ <br>
$P(Error type 2) = P(H_0 not rejected | H_1 true) = 1 - P(H_0 rejected | H_0 true)$

[Back to Table of Contents](../)